// flow-typed signature: a4b34c569d7df92aa2ccc60310d9ca5f
// flow-typed version: <<STUB>>/@react-firebase/auth_v^0.2.9/flow_v0.107.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@react-firebase/auth'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@react-firebase/auth' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@react-firebase/auth/dist/index.cjs' {
  declare module.exports: any;
}

declare module '@react-firebase/auth/dist/index.esm' {
  declare module.exports: any;
}

declare module '@react-firebase/auth/dist/index.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module '@react-firebase/auth/dist/index.cjs.js' {
  declare module.exports: $Exports<'@react-firebase/auth/dist/index.cjs'>;
}
declare module '@react-firebase/auth/dist/index.esm.js' {
  declare module.exports: $Exports<'@react-firebase/auth/dist/index.esm'>;
}
declare module '@react-firebase/auth/dist/index.umd.js' {
  declare module.exports: $Exports<'@react-firebase/auth/dist/index.umd'>;
}
